[package]
name = "aya-test-bpf-common"
version = "0.1.0"
edition = "2018"

[features]
default = []
userspace = [ "aya" ]

[dependencies]
aya = { path = "../../aya/aya", optional=true }

[lib]
path = "src/lib.rs"